#include "main.h"

BSDATA(animationi) = {
	{{"AnimateStand"}},
	{{"AnimateWalk"}},
	{{"AnimatePickup"}},
	{{"AnimateUse"}},
	{{"AnimateDodge"}},
	{{"AnimateDamaged"}},
	{{"AnimateDamagedRear"}},
	{{"AnimateUnarmed1"}},
	{{"AnimateUnarmed2"}},
	{{"AnimateThrown"}},
	{{"AnimateRun"}},
	{{"AnimateKnockOutBack"}, AnimateDeadBackNoBlood, AnimateBloodedBack},
	{{"AnimateKnockOutForward"}, AnimateDeadForwardNoBlood, AnimateBloodedForward},
	{{"AnimateKilledSingle"}, AnimateDeadSingle},
	{{"AnimateKilledBurst"}, AnimateDeadBurst},
	{{"AnimateKilledBurstAuto"}, AnimateDeadBurstAuto},
	{{"AnimateKilledBlowup"}, AnimateDeadBlowup},
	{{"AnimateKilledMelt"}, AnimateDeadMelt},
	{{"AnimateBloodedBack"}, AnimateDeadBack},
	{{"AnimateBloodedForward"}, AnimateDeadForward},
	{{"AnimateStandUpBack"}},
	{{"AnimateStandUpForward"}},
	{{"AnimateDeadBackNoBlood"}},
	{{"AnimateDeadForwardNoBlood"}},
	{{"AnimateDeadSingle"}, AnimateDeadSingle},
	{{"AnimateDeadBurst"}, AnimateDeadBurst},
	{{"AnimateDeadBurstAuto"}, AnimateDeadBurstAuto},
	{{"AnimateDeadBlowup"}, AnimateDeadBlowup},
	{{"AnimateDeadMelt"}, AnimateDeadMelt},
	{{"AnimateDeadBack"}, AnimateDeadBack},
	{{"AnimateDeadForward"}, AnimateDeadForward},
	{{"AnimateWeaponTakeOn"}, AnimateWeaponStand},
	{{"AnimateWeaponStand"}, AnimateWeaponStand},
	{{"AnimateWeaponTakeOff"}},
	{{"AnimateWeaponWalk"}, AnimateWeaponStand},
	{{"AnimateWeaponDodge"}, AnimateWeaponStand},
	{{"AnimateWeaponThrust"}, AnimateWeaponStand},
	{{"AnimateWeaponSwing"}, AnimateWeaponStand},
	{{"AnimateWeaponAim"}, AnimateWeaponSingle},
	{{"AnimateWeaponSingle"}, AnimateWeaponAimEnd},
	{{"AnimateWeaponBurst"}, AnimateWeaponAimEnd},
	{{"AnimateWeaponFlame"}, AnimateWeaponAimEnd},
	{{"AnimateWeaponThrow"}, AnimateWeaponStand},
	{{"AnimateWeaponAimEnd"}, AnimateWeaponStand},
};
assert_enum(animationi, AnimateWeaponAimEnd)