#include "main.h"

BSDATA(stati) = {
	{{"Strenght"}, 0},
	{{"Perception"}, 1},
	{{"Endurance"}, 2},
	{{"Charisma"}, 3},
	{{"Intellegence"}, 4},
	{{"Agility"}, 5},
	{{"Luck"}, 6},
	{{"HP"}, 10, {{15, {Endurance, 2}, {Strenght, 1}}}},
	{{"HPCur"}, 10, {}},
	{{"AP"}, 19, {{5, {Agility, 1, 2}}}},
	{{"APCur"}, 19, {}},
	{{"AC"}, 18, {{0, {}, {}, Kamikaze}, {0, {Agility, 1}}}},
	{{"DamageMelee"}, 21, {{-5, {Strenght, 1}, {}, {}, 1}}},
	{{"DamageMeleeRate"}, -1},
	{{"CarryWeight"}, 20, {{25, {Strenght, 15}, {}, SmallFrame}, {25, {Strenght, 25}}}},
	{{"CriticalHit"}, 26, {{0, {Luck, 1}}}},
	{{"CriticalHitTable"}, -1},
	{{"CriticalMiss"}, -1, {{11, {Luck, -1}}}},
	{{"CriticalMissTable"}, -1},
	{{"Sequence"}, 24, {{0, {Perception, 2}}}},
	{{"PerkRate"}, -1, {{3}}},
	{{"SkillRate"}, -1, {{5, {Intellegence, 2}}}},
	{{"HealingRate"}, 25, {{0, {Endurance, 1, 3}, {}, {}, 1}}},
	{{"PoisonResistance"}, 23, {{0, {}, {}, FastMetabolism}, {0, {Endurance, 5}}}},
	{{"RadiationResistance"}, 83, {{0, {}, {}, FastMetabolism}, {0, {Endurance, 2}}}},
	{{"Age"}},
	{{"Level"}, 7},
	{{"PrimaryPoints"}},
	{{"SkillTagPoints"}},
	{{"SkillPoints"}},
	{{"PoisonPoints"}, 11},
	{{"RadiationPoints"}, 12},
};
assert_enum(stati, LastStat)